# Папка, куда будут загружаться картинки генераторов, виброплит и лестниц
media: assets/images

# Список редактируемых страниц и файлов
content:
  - name: home
    label: "Главная страница"
    type: file
    path: index.html

  - name: catalog
    label: "Каталог техники"
    type: file
    path: catalog.html

  - name: contacts
    label: "Контакты"
    type: file
    path: contacts.html
